package org.ggp.base.player.gamer.statemachine.montecarlo;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

import org.ggp.base.apps.player.config.ConfigPanel;
import org.ggp.base.apps.player.detail.DetailPanel;
import org.ggp.base.apps.player.detail.SimpleDetailPanel;
import org.ggp.base.player.gamer.event.GamerSelectedMoveEvent;
import org.ggp.base.player.gamer.exception.GamePreviewException;
import org.ggp.base.player.gamer.statemachine.StateMachineGamer;
import org.ggp.base.util.game.Game;
import org.ggp.base.util.logging.GamerLogger;
import org.ggp.base.util.statemachine.MachineState;
import org.ggp.base.util.statemachine.Move;
import org.ggp.base.util.statemachine.Role;
import org.ggp.base.util.statemachine.StateMachine;
import org.ggp.base.util.statemachine.cache.CachedStateMachine;
import org.ggp.base.util.statemachine.exceptions.GoalDefinitionException;
import org.ggp.base.util.statemachine.exceptions.MoveDefinitionException;
import org.ggp.base.util.statemachine.exceptions.TransitionDefinitionException;
import org.ggp.base.util.statemachine.implementation.prover.ProverStateMachine;

public class MCTSGamer extends StateMachineGamer
{
    private List<Role> gameRoles = null;
    private Map<Role, Integer> roleIndices = null;
    private Role opponent = null;

    private enum MoveSelection {PESSIMISTIC, MIXED, OPTIMISTIC};

    private Long timeout_buffer = 500L; // In milliseconds

    //TODO: Currently unused - could be used to parallelize depth charges
    private Integer numProbes = 20;

    // This map allows us to keep the previous updates in memory when playing a game.
    // There does not seem to be a significant boost due to this, but it does not
    // cost us too much memory either.
	private HashMap<MachineState, MCTSNode> nodeMap = null;

	private MoveSelection moveSelector = MoveSelection.MIXED;

	// Under memory pressure, new nodes will not be expanded.
	private Double memoryThreshold = 80.0; // Percentage of used memory
	private boolean expandNewNodes = true;

	private Double explorationBias = 40.0;

	// Some statistics about the player
	private long numExpansions = 0;

	private class MCTSNode {
		MachineState state;
		int visits;
		double totalScore;
		double opponentScore;
		MCTSNode parent;

		// Maps each legal move for this player, from this state, to the
		// list of potential game-states generated by making that move.
		HashMap<Move, ArrayList<MCTSNode>> children;

		// This field is not essential, but helps during debug.
		Move 	 parentMove;

		public MCTSNode(MachineState s, int v, double score, double oScore, MCTSNode p, Move m) {
			this.state = s;
			this.visits = v;
			this.totalScore = score;
			this.opponentScore = oScore;
			this.children = new HashMap<Move, ArrayList<MCTSNode>>();
			this.parent = p;
			this.parentMove = m;
		}

		public MCTSNode(MachineState s, MCTSNode p, Move m) {
			this(s,0,0.0,0.0,p,m);
		}

		@Override
		public String toString() {
			StringBuilder sb = new StringBuilder();
			sb.append("State: "+state+"\n");
			sb.append("Visits: "+visits+"\n");
			sb.append("TotalScore: "+totalScore+"\t"+"oScore:"+opponentScore+"\n");
			sb.append("Num children: "+children.size()+"\n");
			sb.append("Parent Move: "+parentMove+"\n");

			return sb.toString();
		}

		public void addChild(MCTSNode child) {
			ArrayList<MCTSNode> siblings = children.get(child.parentMove);

			if (siblings == null) {
				siblings = new ArrayList<MCTSNode>();
				siblings.add(child);
				children.put(child.parentMove, siblings);
			} else {
				siblings.add(child);
			}
		}

	}

	private void log(String s) {
		GamerLogger.log("MCTSGamer", s);
	}

    @SuppressWarnings("serial")
    private class MCTSConfigPanel extends ConfigPanel implements ActionListener {

    	private final String [] mvSelectStrings = {"Pessimistic", "Mixed", "Optimistic"};

        private final JTextField numProbesField;
        private final JTextField timeoutBufferField;
		private final JTextField memoryThresholdField;
		private final JTextField explorationBiasField;

		private final JComboBox<?>  mvSelectField;

        private final MCTSGamer gamer;

        public MCTSConfigPanel(MCTSGamer g) {
            super(new GridBagLayout());
            this.gamer = g;

            //TODO: Is there a more elegant way to add new configuration options?
            numProbesField = new JTextField(gamer.numProbes.toString());
            timeoutBufferField = new JTextField(gamer.timeout_buffer.toString());
        	memoryThresholdField = new JTextField(gamer.memoryThreshold.toString());
        	mvSelectField = new JComboBox<Object>(mvSelectStrings);
        	mvSelectField.setSelectedIndex(gamer.moveSelector.ordinal());
        	explorationBiasField = new JTextField(gamer.explorationBias.toString());

            numProbesField.addActionListener(this);
            timeoutBufferField.addActionListener(this);
			memoryThresholdField.addActionListener(this);
			mvSelectField.addActionListener(this);
			explorationBiasField.addActionListener(this);

            this.add(new JLabel("Number of probes:"),
            		new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0,
            				GridBagConstraints.EAST, GridBagConstraints.NONE,
            				new Insets(20, 5, 5, 5), 5, 5));
            this.add(numProbesField,
            		new GridBagConstraints(1, 0, 1, 1, 1.0, 0.0,
            				GridBagConstraints.CENTER, GridBagConstraints.HORIZONTAL,
            				new Insets(20, 5, 5, 5), 5, 5));

            this.add(new JLabel("Timeout Buffer:"),
            		new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0,
            				GridBagConstraints.EAST, GridBagConstraints.NONE,
            				new Insets(5, 5, 5, 5), 5, 5));
            this.add(timeoutBufferField,
            		new GridBagConstraints(1, 1, 1, 1, 1.0, 0.0,
            				GridBagConstraints.CENTER, GridBagConstraints.BOTH,
            				new Insets(5, 5, 5, 5), 5, 5));

            this.add(new JLabel("Memory Threshold(%):"),
            		new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0,
            				GridBagConstraints.EAST, GridBagConstraints.NONE,
            				new Insets(5, 5, 5, 5), 5, 5));
            this.add(memoryThresholdField,
            		new GridBagConstraints(1, 2, 1, 1, 1.0, 0.0,
            				GridBagConstraints.CENTER, GridBagConstraints.BOTH,
            				new Insets(5, 5, 5, 5), 5, 5));

            this.add(new JLabel("Move Selection:"),
            		new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0,
            				GridBagConstraints.EAST, GridBagConstraints.NONE,
            				new Insets(5, 5, 5, 5), 5, 5));
            this.add(mvSelectField,
            		new GridBagConstraints(1, 3, 1, 1, 1.0, 0.0,
            				GridBagConstraints.CENTER, GridBagConstraints.BOTH,
            				new Insets(5, 5, 5, 5), 5, 5));

            this.add(new JLabel("Exploration Bias:"),
            		new GridBagConstraints(0, 4, 1, 1, 0.0, 0.0,
            				GridBagConstraints.EAST, GridBagConstraints.NONE,
            				new Insets(5, 5, 5, 5), 5, 5));
            this.add(explorationBiasField,
            		new GridBagConstraints(1, 4, 1, 1, 1.0, 0.0,
            				GridBagConstraints.CENTER, GridBagConstraints.BOTH,
            				new Insets(5, 5, 5, 5), 5, 5));

        }

        @Override
        public void actionPerformed(ActionEvent e) {

			try {
				if (e.getSource() == numProbesField) {
					gamer.numProbes = Integer.valueOf(numProbesField.getText());
				} else if (e.getSource() == timeoutBufferField) {
					gamer.timeout_buffer = Long.valueOf(timeoutBufferField.getText());
				} else if (e.getSource() == memoryThresholdField) {
					System.out.println("Updating Memory Threshold");
					gamer.memoryThreshold = Double.valueOf(memoryThresholdField.getText());
				} else if (e.getSource() == mvSelectField) {
					int selection = mvSelectField.getSelectedIndex();
					gamer.moveSelector = MoveSelection.values()[selection];
				} else if (e.getSource() == explorationBiasField) {
					gamer.explorationBias = Double.valueOf(explorationBiasField.getText());
				}
			} catch (Exception ex) {
				System.err.println("Error when updating configuration; Changes have not been saved.");
				ex.printStackTrace();
			}

        }

    }

    @Override
    public void stateMachineMetaGame(long timeout) throws TransitionDefinitionException, MoveDefinitionException, GoalDefinitionException
    {
        //TODO: Do something useful during the meta-game phase.
    }

    @Override
    public String getName() {
        return getClass().getSimpleName();
    }

    @Override
    public StateMachine getInitialStateMachine() {
        return new CachedStateMachine(new ProverStateMachine());
    }

    @Override
    public DetailPanel getDetailPanel() {
        return new SimpleDetailPanel();
    }

    @Override
    public ConfigPanel getConfigPanel() {
        return new MCTSConfigPanel(this);
    }

    @Override
    public void stateMachineStop() {
        gameRoles = null;
        roleIndices = null;
        opponent = null;
		nodeMap = null;
    }

    @Override
    public void stateMachineAbort() {
        gameRoles = null;
        roleIndices = null;
        opponent = null;
		nodeMap = null;
    }

    @Override
    public void preview(Game g, long timeout) throws GamePreviewException {
    }

    private Move getRandomMove() throws MoveDefinitionException {
        List<Move> moves = getStateMachine().getLegalMoves(getCurrentState(), getRole());
		return (moves.get(new Random().nextInt(moves.size())));
    }

	private double utility(MCTSNode node, boolean inverse) {
		double averageScore = node.totalScore / node.visits;
		if (inverse)
			averageScore *= -1;
		return averageScore + explorationBias*Math.sqrt(2*Math.log(node.parent.visits)/node.visits);
	}

	private double oUtility(MCTSNode node) {
		double averageScore = node.opponentScore / node.visits;
		return averageScore + explorationBias*Math.sqrt(2*Math.log(node.parent.visits)/node.visits);
	}

	private MCTSNode select(MCTSNode root) {

		MCTSNode current = root;

		while (true) {

			if (current.visits == 0 || getStateMachine().isTerminal(current.state))
				return expandNewNodes?current:(current.parent==null?current:current.parent);

			for (Map.Entry<Move, ArrayList<MCTSNode>> siblings : current.children.entrySet()) {
				for (MCTSNode child : siblings.getValue()) {
					if (child.visits == 0)
						return expandNewNodes?child:current;
				}
			}

			double score = Double.NEGATIVE_INFINITY;
			MCTSNode bestChild = current;

			for (Map.Entry<Move, ArrayList<MCTSNode>> siblings : current.children.entrySet()) {
				MCTSNode bestSibling = null;
				double   siblingScore = Double.NEGATIVE_INFINITY;
				double   siblingOScore = Double.NEGATIVE_INFINITY;

				for (MCTSNode child : siblings.getValue()) {
					double newScore = Double.NEGATIVE_INFINITY;
					if (moveSelector == MoveSelection.PESSIMISTIC) {
						newScore = utility(child, true);
						if (newScore > siblingScore) {
							siblingScore = utility(child, false);
							bestSibling = child;
							//assert child.parent == current;
							// A node may have multiple parents - visit the right one
							// when back propagating.
							child.parent = current;
							child.parentMove = siblings.getKey();
						}
					} else if (moveSelector == MoveSelection.MIXED) {
						newScore = oUtility(child);
						if (newScore > siblingOScore) {
							siblingOScore = newScore;
							siblingScore = utility(child, false);
							bestSibling = child;
							//assert child.parent == current;
							// A node may have multiple parents - visit the right one
							// when back propagating.
							child.parent = current;
							child.parentMove = siblings.getKey();
						}
					} else if (moveSelector == MoveSelection.OPTIMISTIC) {
						newScore = utility(child,false);
						if (newScore > siblingScore) {
							siblingScore = newScore;
							bestSibling = child;
							child.parent = current;
							child.parentMove = siblings.getKey();
						}
					}

				}

				if (siblingScore > score) {
					score = siblingScore;
					bestChild = bestSibling;
				}
			}

			assert bestChild != current;
			current = bestChild;
		}
	}

	private void expand(MCTSNode node) throws MoveDefinitionException, TransitionDefinitionException,
			GoalDefinitionException {

		//log("************************EXPAND************************\n");
		//log("Expanding Node: "+node.toString());

		if (getStateMachine().isTerminal(node.state))
			return;

		Map<Move, List<MachineState>> nextStates = getStateMachine().getNextStates(node.state, getRole());

		for (Map.Entry<Move,List<MachineState>> entry: nextStates.entrySet()) {
			MCTSNode child         = null;
			Move 	 parentMove    = entry.getKey();

			for (MachineState s : entry.getValue()) {
				child = nodeMap.get(s);
				if (child == null) {
					child = new MCTSNode(s,node,parentMove);
					nodeMap.put(child.state, child);
				} else {
					child.parent = node;
					child.parentMove = parentMove;
				}
				node.addChild(child);
				//log("Adding new child: "+child.toString());
			}
		}

		//log("**********************************************************\n");
	}

	private void backpropagate(MCTSNode leaf, double [] scores) {

		MCTSNode current = leaf;

		int pIndex = roleIndices.get(getRole());
		int oIndex = 0;
		if (opponent != null) {
			oIndex = roleIndices.get(opponent);
		}

		while (current != null) {
			current.visits++;

			current.totalScore += scores[pIndex];

			if (opponent != null) {
				current.opponentScore += scores[oIndex];
			}

			current = current.parent;
		}
	}

    private Move getMove() throws TransitionDefinitionException, MoveDefinitionException,
                          GoalDefinitionException{
        if (gameRoles == null)
            gameRoles = getStateMachine().getRoles();

        if (roleIndices == null)
            roleIndices = getStateMachine().getRoleIndices();

        if (opponent == null) {
            opponent = getOpponent();
        }

		if (nodeMap == null) {
			nodeMap = new HashMap<MachineState, MCTSNode>();
		}

		numExpansions = 0;

		List<Move> moves = getStateMachine().getLegalMoves(getCurrentState(),getRole());
		if (moves.size() == 1)
			return moves.get(0);

		MCTSNode currentNode = nodeMap.get(getCurrentState());
		if (currentNode == null) {
			currentNode = new MCTSNode(getCurrentState(), null, null);
			nodeMap.put(getCurrentState(), currentNode);
		}
		currentNode.parent = null;
		currentNode.parentMove = null;

		double usedPercent=(double)(Runtime.getRuntime().totalMemory()
				-Runtime.getRuntime().freeMemory())*100.0/Runtime.getRuntime().maxMemory();

		System.out.println("Used Memory: "+usedPercent+"%");
		System.out.println("MEMORY THRESHOLD: "+memoryThreshold);
		expandNewNodes = true;

		if (usedPercent >= memoryThreshold) {
			System.out.println("Memory threshold exceeded - new states will not be expanded");
			expandNewNodes = false;
		}


		while (true) {
			MCTSNode selection = select(currentNode);

			if (expandNewNodes)
				expand(selection);

			List<Integer> scoresList = depthCharge(selection.state);

			double [] scores = new double[scoresList.size()];
			for (int i=0; i<scoresList.size(); i++)
				scores[i] = scoresList.get(i);

			backpropagate(selection, scores);

			numExpansions++;
		}

    }

	private Move getBestMove() throws MoveDefinitionException {

		MCTSNode current = nodeMap.get(getCurrentState());

		Move   bestMove  = null;
		double score = Double.NEGATIVE_INFINITY;

		log("**********************Best Move******************************\n");
		GamerLogger.log("MCTSGamer", "Current State: "+current.state+"\n");
		GamerLogger.log("MCTSGamer", "Children:\n");
		for (Map.Entry<Move, ArrayList<MCTSNode>> siblings : current.children.entrySet()) {
			double   siblingScore = Double.POSITIVE_INFINITY;
			double   siblingOScore = Double.NEGATIVE_INFINITY;
			Move 	 currentMove = siblings.getKey();

			for (MCTSNode child : siblings.getValue()) {
				GamerLogger.log("MCTSGamer", child.toString());
				double newScore = child.totalScore/child.visits;
				double oScore   = 0.0;

				if (opponent != null) {
					oScore = child.opponentScore / child.visits;
				}

				if (moveSelector == MoveSelection.PESSIMISTIC) {
					if (newScore < siblingScore) {
						siblingScore = newScore;
					}
				} else if(moveSelector == MoveSelection.MIXED) {
					if (oScore > siblingOScore) {
						siblingOScore = oScore;
						siblingScore = newScore;
					}
				} else if(moveSelector == MoveSelection.OPTIMISTIC) {
					if (newScore > siblingScore) {
						siblingScore = newScore;
					}
				}
			}

			if (siblingScore > score) {
				score = siblingScore;
				bestMove = currentMove;
			}
		}

		log("***********************************************************************\n");

		if (bestMove != null)
			return bestMove;
		else {
			System.out.println("No good move found, choosing randomly");
			return getRandomMove();
		}

	}

    /*
     * This function is called at the start of each round
     * You are required to return the Move your player will play
     * before the timeout.
     *
     */
    @Override
    public Move stateMachineSelectMove(long timeout)
        throws TransitionDefinitionException, MoveDefinitionException,
                          GoalDefinitionException
    {

        // We get the current start time
        long start = System.currentTimeMillis();

        System.out.println("TIMEOUT: "+(timeout-start));

        ExecutorService exec = Executors.newSingleThreadExecutor();
        Future<Move> f = exec.submit(new Callable<Move>() {
            @Override
			public Move call() throws TransitionDefinitionException, MoveDefinitionException,
                          GoalDefinitionException {
                return getMove();
            }
        });

        Move selection = null;

        try {
            selection = f.get(timeout - start - timeout_buffer, TimeUnit.MILLISECONDS);
        } catch (TimeoutException e) {
            System.out.println("getMove() timed-out");
            exec.shutdownNow();
			selection = getBestMove();
        } catch (Exception e) {
            System.out.println("getMove() was interrupted");
		    GamerLogger.logStackTrace("GamePlayer", e);
            selection = getRandomMove();
        }


		log("Num Expansions: "+numExpansions);
		log("Size of Node-map: "+nodeMap.size());
		//nodeMap = null;
        // We get the end time
        // It is mandatory that stop<timeout
        long stop = System.currentTimeMillis();

        /**
         * These are functions used by other parts of the GGP codebase
         * You shouldn't worry about them, just make sure that you have
         * moves, selection, stop and start defined in the same way as
         * this example, and copy-paste these two lines in your player
         */
        notifyObservers(new GamerSelectedMoveEvent(
                    getStateMachine().getLegalMoves(getCurrentState(), getRole()), selection, stop - start));
        return selection;
    }

    // TODO: Extend this for games with >2 players?
    private Role getOpponent() {
        for (Role r : gameRoles) {
            if (!r.equals(getRole()))
                return r;
        }

        return null;
    }

	private List<Integer> depthCharge(MachineState s) {
		try {
			MachineState fs = getStateMachine().performDepthCharge(s,null);
			return getStateMachine().getGoals(fs);
		} catch (Exception e) {
			e.printStackTrace();
			return null;
		}
	}

}
